#
# Copyright (C) 2015   Michael Lahnert
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# add possibility to add a debug visu
vars = Variables('custom.py')
vars.Add (BoolVariable('visu', 'Set to 1 for enabling debug visu', 0))
vars.Add (BoolVariable('debug', 'Set to 1 to enable debug flags', 0))
vars.Add (BoolVariable('vtk', 'Set to 1 to enable vtk output', 0))
vars.Add (BoolVariable('heat', 'Set to 1 to enable heat coupling', 0))

cppdefines = []

env = Environment(variables=vars,CPPDEFINES = cppdefines)

# parallel
env.Replace(CXX='g++')

#serial
# env.Replace(CXX='g++')

# define some general compiler flags
env.Append(
           CXXFLAGS=[
                     "-Wall",
                     "-Wextra",
                     "-pedantic",
                     "-std=c++0x",
           ],
           LIBS=[
                 "OpenCL",
           ]
          )

if env['visu']:
    env['LIBS'] += ["SDL2"]
 
if env['vtk']:
    env['CPPDEFINES'] += ["VTK_OUTPUT"]
    
if env['heat']:
    env['CPPDEFINES'] += ["HEAT_COUPLING"]

# add flags for debug and release build
if not env['debug']:
    env['CXXFLAGS'] += ["-O3","-flto"]
    env['LINKFLAGS'] += ["-flto"]
else:
    env['CXXFLAGS'] += [
                        "-g3",
                        "-O0",
                       ]

# call SConscript to actually build the project after setting up the environment
env.SConscript("./SConscript", exports='env', variant_dir='./build', duplicate=0)
